### ISSUE TITLE
.NET Core / .NET 5 & SharpBrick.PoweredUp

### ISSUE THREAD

**Issue by tthiery** [Cosmik42/BAP#1]
Hi @Cosmik42 

thanks for open sourcing! A month or two I stumbled over your project and wanted to control my Control+ stuff with it. Well, it was not open source then. So, well, meanwhile, I created an C# NuGet library [sharpbrick/powered-up](https://github.com/sharpbrick/powered-up) for communicating with my `TechnicMediumHub` and its motors. The library is not a user interface and - at the current stage - does not support yet the typical train equipment (like the 88009 Hub etc). But I (maybe we) are on the way.

I am collecting allies right now to create a meaningful C# / .NET community around PoweredUp. Would you be interested in collaborating?

cc
@mattze0815

**Comment by Cosmik42** [comment]
Hi Mattze,

Unfortunately the very reason I am going open source is because I have no personal time I can dedicate to this project anymore and unfortunately won't be able to help you :(
